// import React from 'react'
import Head from 'next/head';
import Link from 'next/link';

import style from '../layout/Layout.module.css';

function Layout(props: any) {
    return (
      <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={style.header}>
            <h1><Link href={`/`} style={{color: 'white', textDecoration: 'none'}}>Personajes de Rick and Morty</Link></h1>
        </header>
        {props.children}
      </>
    )
  }
  
  export default Layout
